# Generated by Django 4.1.7 on 2023-02-28 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuitem_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='sub_items',
            new_name='parent',
        ),
    ]
